### ISSUE TITLE
Select which kinds of components to return

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python-recurring-ical-events#101]
Before v1.1.0, the library returned only events. Now, it is also returning other component types, see #97.
I am unsure if my code breaks when I update! https://github.com/niccokunzmann/open-web-calendar/pull/136 (yep, not everything is TDD with me :)

I would like to propose a way to
- by default only return events
- additionally add components that we also like

```
events = recurring_ical_events.of(calendar).between(...)
journals = recurring_ical_events.of(calendar, components=["VJOURNAL"]).between(...)
todos = recurring_ical_events.of(calendar, components=["VTODO"]).between(...)
all = recurring_ical_events.of(calendar, components=["VTODO", "VEVENT", "VJOURNAL"]).between(...)
```

It almost looks like we should do

```
events = recurring_ical.events.of(calendar).between(...)
todos = recurring_ical.todos.of(calendar).between(...)
journals = recurring_ical.journals.of(calendar).between(...)
```
But I can see that you might want them all in one place - so this might be not the right design. Renaming the library to `recurring_ical_components` might also be a nice step.

@tobixen this is interesting to you.

**Comment by tobixen** [comment]
Renaming the library feels a bit "nuclear option".

I think the default should be to return all components.

**Comment by tobixen** [comment]
There are several calendar servers today that supports recurring events, but not recurring tasks.  Perhaps some of them are using this library.  Perhaps they will magically start returning recurring tasks as well when upgrading the library.  Wishful thinking, maybe :-)

**Comment by tobixen** [comment]
But it is nice that the library name matches what it's doing (by default), so ... no further complaints from my side :-)

**Comment by niccokunzmann** [comment]
The fix is shipped in version 2.0.0.

**Comment by tobixen** [comment]
I had completely forgotten about this one, I suppose this explains https://github.com/python-caldav/caldav/issues/241 :-)

**Comment by niccokunzmann** [comment]
Maybe. You seem to fix the version of your dependencies though.
