### ISSUE TITLE
Support for RRULE with COUNT

### ISSUE THREAD

**Issue by natashamm** [niccokunzmann/python-recurring-ical-events#106]
Could support for recurrence rules (`RRULE`) with a `COUNT` parameter be added?

Background: `RRULE` can have one of `COUNT`, `UNTIL` or neither. See [RFC 2445 Section 4.8.5.4](https://www.rfc-editor.org/rfc/rfc2445#section-4.8.5.4) for more info.

**Comment by niccokunzmann** [comment]
I wonder: Do you have an example file?
I thought it would be supported. Hm. I agree that it is important to support it.

**Comment by natashamm** [comment]
Thank you for your response. I tested it with another "cleaner" `COUNT` and it seemed to work.

It might be another weird attribute in the calendar, unfortunately I can't share the calendar, but I will provide an update here if I think it might be of interest. Closing the issue.
