### ISSUE TITLE
Claiming compatibility to other RFCs/updates of RFC5545

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python-recurring-ical-events#125]
These RFCs are updates to RFC5545. For each of them, it would be nice to check if we can claim that recurring-ical-events is compatible.

- [x] RFC 6868 (parsing, not affected)
- [x] RFC 7529
- [x] RFC 7953
- [x] RFC 7986 (not for recurrence)
- [x] RFC 9073 (not for recurrence)
- [x] RFC 9074 (not for recurrence)
- [x] RFC 9253 (not for recurrence)

See also:
- https://www.rfc-editor.org/info/rfc5545

This issue can be closed when
- [x] all of them are checked (possibly with tests)
- [ ] we say in the README if we are compatible or not

See also: https://github.com/collective/icalendar/issues/589

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/python-recurring-ical-events/issues/125">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/125/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/125/pledge.svg">
</picture>
</a>

**Comment by tobixen** [comment]
I was doing a similar job earlier wrg of my `calendar-cli`/`plann` and `caldav` projects.  I won't promise when/if I have time, but I'll put on my list that I will look into those RFCs and flag things that may and may not be relevant for the recurring ical project.

**Comment by niccokunzmann** [comment]
Thanks! I see when I have time, too.
