### ISSUE TITLE
bug: Failure to parse this weird timezone: tzone://Microsoft/Utc

### ISSUE THREAD

**Issue by KonstantinSchubert** [niccokunzmann/python-recurring-ical-events#126]
First of: I *love* this library, it has been a godsend! I discovered after an afternoon of losing my mind with ics recurrence...

Anyways, I found a minor feature gap that may or may not be intentional: 

**To Reproduce**
In the context of me calling this function:
```
events = recurring_ical_events.of(ical).between(
        time_range_start, time_range_end
    )
```

It returned an event with a timezone-naive start and end time. 

The underlying event in the .ics file was:
```
BEGIN:VEVENT
UID:<redacted>
SUMMARY:<redacted>
DTSTART;TZID="tzone://Microsoft/Utc":20240116T203000
DTEND;TZID="tzone://Microsoft/Utc":20240116T210000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20240116T151612Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:1
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:1
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-ISRESPONSEREQUESTED:FALSE
END:VEVENT
```

So this clearly uses a very weird timezone that is apparently not supported. 

Is there a way to add support for this timezone? I am willing to help, but it's probably just a `.replace` somewhere...

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/python-recurring-ical-events/issues/126">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/126/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/126/pledge.svg">
</picture>
</a>

**Comment by KonstantinSchubert** [comment]
here is how other people handled this: 

https://github.com/ecederstrand/exchangelib/commit/e3b11331d98c6c5dcddd9852f53944b6de01ccfa

**Comment by KonstantinSchubert** [comment]
My bad, this has to be fixed in the `icalendar` library. Sorry for the confusion.

**Comment by niccokunzmann** [comment]
@KonstantinSchubert Feel free to open an issue there, too!
