### ISSUE TITLE
Pytz recursive version conflict

### ISSUE THREAD

**Issue by ashkuren** [niccokunzmann/python-recurring-ical-events#14]
Hello,

The project fixes `pytz` version to `2018.9` (mentiones via icalendar), whereas `icalendar` does not mention any specific `pytz` version in dependencies. This gives a dependency loop issue that can appear when `icalendar` is installed before `recurring-ical-events` (current `pytz` version is 2019.3).

Moreover, `pytz` is not used in the project itself, but only in tests. I think, it's better to leave only `icalendar` and `dateutil` as a dependency and move `pytz` without specific version to `test-requirements.txt`.

**Comment by niccokunzmann** [comment]
Hi and thanks for reporting this. Feel free to submit a pull request
which fixes it in your view.
