### ISSUE TITLE
KeyError "SEQUENCE"

### ISSUE THREAD

**Issue by firrm** [niccokunzmann/python-recurring-ical-events#15]
When using the wounderful  [open-web-calendar](https://github.com/niccokunzmann/open-web-calendar) I experienced with some calendars (origin: nextcloud) a KeyError "SEQUENCE" which steams from this package.

Traced the error back to line 288:
if event["SEQUENCE"] < other["SEQUENCE"]:

here other has no entry "SEQUENCE" which must be something to do with the calendars's file.

However quick solutio is adding
if isinstance(event.get("SEQUENCE"), int) and isinstance(other.get("SEQUENCE"),int):
before  the if-clause

**Comment by niccokunzmann** [comment]
Wow, thanks for reporting this!
So, if you like, you can create a pull request.
This library is test-driven to ensure future compatibility while
allowing for refactorings, so...
If you have an ICS file, you can add it and it can be tested.

If you like to have the change soon, I can guide you through the process
of changing the library.

Best,
Nicco

**Comment by niccokunzmann** [comment]
@firrm, as you can see in #11, providing a test case speeds up fixing this. If you have one, let me know. The thing is - I do not track the requests and errors and as such do not know which ical files fail.

**Comment by niccokunzmann** [comment]
This should be fixed from version v0.1.12b0 on.
