### ISSUE TITLE
bug: Series.__init__ raise errors on bad events even if skip_bad_series is true

### ISSUE THREAD

**Issue by fabien-michel** [niccokunzmann/python-recurring-ical-events#172]
In `Series.__init__`, there are 2 exceptions raised : [here](https://github.com/niccokunzmann/python-recurring-ical-events/blob/e91959369106031d61161014557817fbb3a94648/recurring_ical_events.py#L311) and [here](https://github.com/niccokunzmann/python-recurring-ical-events/blob/e91959369106031d61161014557817fbb3a94648/recurring_ical_events.py#L335)

It seems that these errors are linked to a malformed event. In that case they should be skiped/quiet if skip_bad_series is true.

I suggest, to make specific exceptions for these two cases and default make them skipable.

```python
class NoComponentEvent(InvalidCalendar):
    """An event has no component"""


class OnlyModificationsEvent(InvalidCalendar):
    """A component only contains modifications"""

    def __init__(self, message: str, uid: str):
        """Create an error with component uid."""
        super().__init__(message + ": " + uid)
        self._uid = uid

    @property
    def uid(self) -> str:
        """The uid of the component"""
        return self._uid

```

```python
...
raise NoComponentEvent("No components given to calculate a series.")
...
raise OnlyModificationsEvent(
    f"The event definition for {components[0].uid} "
    "only contains modifications.",
    components[0].uid,
)
...

suppressed_errors = [
        BadRuleStringFormat,
        PeriodEndBeforeStart,
        OnlyModificationsEvent,
        NoComponentEvent,
]

...
```

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/python-recurring-ical-events/issues/172">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/172/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/172/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
This sounds like a lovely suggestion! Indeed we would want those to be skipped. At the same time: If we have an event series and it does not have a 'core' event but only recurrences specified, we could assume that these recurrences should be part of the results. That is probably another issue but also related if the error messages are removed due to that. What are your thoughts as a default on this? It would not be a 'skip bad events' rather we would incorporate those into the event series. I will check your other issue...

**Comment by niccokunzmann** [comment]
In some way, for this specific error, I would say that this is a duplicate of #173.

**Comment by gpkvt** [comment]
At least for my usecase 3.3.0 fixed this issue. Thanks!

**Comment by fabien-michel** [comment]
Thanks, all our calendars previously crashing on it, now pass !
