### ISSUE TITLE
bug: event is raising "only contains modifications" error

### ISSUE THREAD

**Issue by fabien-michel** [niccokunzmann/python-recurring-ical-events#173]
The following event is [raising a `only contains modifications` error](https://github.com/niccokunzmann/python-recurring-ical-events/blob/e91959369106031d61161014557817fbb3a94648/recurring_ical_events.py#L335)

It is generated by google calendar. In fact I got a lot of them from google calendars.

I'm not sure it is a legitimate error, but maybe I do not understand something.

```ical
BEGIN:VEVENT
SUMMARY:XXX
DTSTART;TZID=Europe/Paris:20210128T103000
DTEND;TZID=Europe/Paris:20210128T123000
DTSTAMP:20240905T100311Z
UID:xxx@google.com
RECURRENCE-ID;TZID=Europe/Paris:20210128T103000
SEQUENCE:2
ATTENDEE;CN=xxx@yyy.com;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS
 -ACTION;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:xxx@yyy.com
ATTENDEE;CN=xxx@yyy.com;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTE
 D;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:xxx@yyy.com
ATTENDEE;CN=xxx@yyy.com;CUTYPE=INDIVIDUAL;PARTSTAT=ACC
 EPTED;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:xxx@yyy.com
ATTENDEE;CN=xxx@yyy.com;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEP
 TED;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:xxx@yyy.com
ATTENDEE;CN=xxx@yyy.com;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-AC
 TION;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:xxx@yyy.com
CREATED:20201217T141214Z
DESCRIPTION:XXX
LAST-MODIFIED:20230121T015157Z
ORGANIZER;CN=xxx@yyy.com:mailto:xxx@yyy.com
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
```

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/python-recurring-ical-events/issues/173">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/173/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/173/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
Hi, thanks for reporting this! Could you attach the whole ICS file for this? Is there an ICS file or is it only this event?

**Comment by fabien-michel** [comment]
Here is a full ics from google calendar (anonymized) which trigger the error

[negawatt.ics.zip](https://github.com/user-attachments/files/16904986/negawatt.ics.zip)

```
recurring_ical_events.OnlyModificationsEvent: The event definition for _6krj2dhl74q34b9j60sj4b9k8h238b9p6gok2ba68gojgchl6cpj0h1o88_R20231009T130000@google.com only contains modifications.: _6krj2dhl74q34b9j60sj4b9k8h238b9p6gok2ba68gojgchl6cpj0h1o88_R20231009T130000@google.com
```

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
Quoting https://github.com/niccokunzmann/python-recurring-ical-events/issues/172#issuecomment-2334392472

> ... If we have an event series and it does not have a 'core' event but only recurrences specified, we could assume that these recurrences should be part of the results. [...] we would incorporate those into the event series. [...]

If Google Calendar creates these events, I wonder what is meant by that. Do they turn up in the online calendar?
Do you see an event at 2021 Jan 28  at 10:30 (Paris Time) in the calendar? I will check the RFC...

**Comment by AttilaPazmandi** [comment]
Hi,

I have the same problem
 ```ical
BEGIN:VEVENT
DESCRIPTION:<...>\n______________________________________________________
 __________________________\n\n
UID:040000008200E00074C5B7101A82E00800000000401FEA87490EDA01000000000000000
 010000000F9112D922FE20E4DB34316608DEC223F
RECURRENCE-ID;TZID=W. Europe Standard Time:20231116T100000
SUMMARY:<Title>
DTSTART;TZID=W. Europe Standard Time:20231128T100000
DTEND;TZID=W. Europe Standard Time:20231128T110000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20240909T121901Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:10
LOCATION:Microsoft Teams Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:10
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-ISRESPONSEREQUESTED:FALSE
END:VEVENT
```
It throws the following:
`File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 335, in __init__
    raise InvalidCalendar(
recurring_ical_events.InvalidCalendar: The event definition for 040000008200E00074C5B7101A82E00800000000401FEA87490EDA01000000000000000010000000F9112D922FE20E4DB34316608DEC223F only contains modifications.`
It is visible in my calendar on the 28th of November, 2023 at 10AM.

**Comment by niccokunzmann** [comment]
@AttilaPazmandi, could you also attach an ICS file?

**Comment by niccokunzmann** [comment]
For this issue, I would not skip the events. I believe that it can happen e.g. if you accept a calendar invitation with a recurring event. Thus, the event should be included in the results.

**Comment by fabien-michel** [comment]
Thanks, all our calendars previously crashing on it, now pass !
