### ISSUE TITLE
Resepect recurring events with instances cancelled within a separate VEVENT

### ISSUE THREAD

**Issue by wichmannpas** [niccokunzmann/python-recurring-ical-events#18]
Some clients (e.g., Business Calendar on Android) cancel deleted instances from a recurring event by explicitly adding another `VEVENT` object for that particular date with `CANCELLED` status. `recurring_ical_events` currently does not respect these, but returns the events from the main event with the original status.

It would be helpful if it respected that way of deleting recurring events.

**Comment by niccokunzmann** [comment]
@wichmannpas Thanks for reporting this. Can you copy and paste an ICS-example into this issue? Then, we can create tests and add the feature. This would be the workflow:

- [ ] ICS example https://github.com/niccokunzmann/python-recurring-ical-events/tree/master/test/calendars
- [ ] add a test Example:
    https://github.com/niccokunzmann/python-recurring-ical-events/blob/f4a90b211f30bf0522f03514ba50eb69826f0fdb/test/test_issue_15.py#L21
- [ ] implement the test

**Comment by niccokunzmann** [comment]
Hm. I found this about status: https://www.kanzaki.com/docs/ical/status.html
I suspect that the event is not removed, then but should receive the cancel status.

**Comment by niccokunzmann** [comment]
I created three events and cancelled one of them. Creating tests.

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20200206T210738Z
LAST-MODIFIED:20200206T210826Z
DTSTAMP:20200206T210826Z
UID:b65c2b5b-b785-4edc-9560-e0379036d1f2
SUMMARY:one is cancelled
RRULE:FREQ=DAILY;COUNT=3
DTSTART;TZID=Europe/Berlin:20200128T220000
DTEND;TZID=Europe/Berlin:20200128T230000
TRANSP:OPAQUE
X-MOZ-GENERATION:3
SEQUENCE:1
END:VEVENT
BEGIN:VEVENT
CREATED:20200206T210806Z
LAST-MODIFIED:20200206T210826Z
DTSTAMP:20200206T210826Z
UID:b65c2b5b-b785-4edc-9560-e0379036d1f2
SUMMARY:one is cancelled
STATUS:CANCELLED
RECURRENCE-ID;TZID=Europe/Berlin:20200129T220000
DTSTART;TZID=Europe/Berlin:20200129T220000
DTEND;TZID=Europe/Berlin:20200129T230000
LOCATION:
DESCRIPTION:
TRANSP:OPAQUE
CLASS:
SEQUENCE:2
END:VEVENT
END:VCALENDAR
```
