### ISSUE TITLE
bug: some datetime timezone formats cause problems for the `between` method.

### ISSUE THREAD

**Issue by RagingRoosevelt** [niccokunzmann/python-recurring-ical-events#26]
**Describe the bug**
Depending on how I create start and end datetimes, the `between` method can produce an `AttributeError: 'datetime.timezone' object has no attribute 'localize'`.

The stack trace points to [here](https://github.com/niccokunzmann/python-recurring-ical-events/blob/v0.1.16b0/recurring_ical_events.py#L226) as the source of the problem.  I imagine that maybe the `start.tzinfo is not None` test on the line above should test for something more specific?

**To Reproduce**
```python
import datetime as dt
now = dt.datetime.now().astimezone(tz=None)
dt_start = (now + dt.timedelta(days=now.isoweekday() % 7))
dt_end = (now + dt.timedelta(days=27+now.isoweekday() % 7))

recurring_ical_events.of(cal).between(
    dt_start,
    dt_end
)
```

when I fetch the `tzinfo` attribute for `now`, `dt_start`, and `dt_end`, I get `datetime.timezone(datetime.timedelta(-1, 57600), 'Pacific Standard Time')` and it appears that `datetime.timezone` generally doesn't have a `localize` method.

I also tried this without the `.astimezone(tz=None)` when setting `now` and with that removed, I instead get a `TypeError: can't compare offset-naive and offset-aware datetimes`.   Same goes for if I use year/month/date tuples for start and end.

**ICS file**
 

```python
from ics import Calendar
import requests
url = "https://calendar.google.com/calendar/ical/<my email>%40gmail.com/private-<secret key>/basic.ics"
c = Calendar(requests.get(url).text)
```

**Version:**
 
![](https://raster.shields.io/badge/version-0.1.16b0-brightgreen.png)

**Comment by niccokunzmann** [comment]
Hi and thanks for reporting!
So, this seems like two errors you encounter. 

This library is developed in a test-driven way to ensure future compatibility.
If you like, you can add an ICS file or even a test. It is possible, to edit the file and remove all personal information.
How far are you willing to go?

I wonder if one will get the same errors using the ICS files I have in the repository. That would be idea for how to go about it in the next step. So, thanks for the code - it will make things easier.

**Comment by RagingRoosevelt** [comment]
I tried a couple of the icals you have in the repo and couldn't reproduce the error.  I also created a new google account and couldn't reproduce the error with the ical I downloaded from that account's calendar.  I'm going to see if I can track down what in my google calendar's ical is creating the issue.

**Comment by RagingRoosevelt** [comment]
OK, this seems to reliably reproduce the `TypeError: can't compare offset-naive and offset-aware datetimes` exception.

```python
from icalendar import Calendar
import recurring_ical_events
import datetime as dt

gcal = Calendar.from_ical(open('google calendar.ics', 'r').read())

# NOTE: this statement for 'now' can be replaced with 
# now = dt.datetime.now().astimezone(tz=None)
# and was also causing the error.  I just wanted to save exactly what I was running.
# However, if I use 
# now = dt.datetime.now()
# I don't encounter the error any more.
now = dt.datetime(2020, 3, 1, 15, 16, 27, 667812, tzinfo=dt.timezone(dt.timedelta(-1, 57600), 'Pacific Standard Time'))
dt_start = (now + dt.timedelta(days=now.isoweekday() % 7))
dt_end = (now + dt.timedelta(days=27+now.isoweekday() % 7))


recurring_ical_events.of(gcal).between(
    dt_start,
    dt_end
)
```

using the following as the ics file:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:fortesting833@gmail.com
X-WR-TIMEZONE:America/Los_Angeles
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Dentist Cleaning
DTSTART:20200417T210000Z
DTEND:20200417T220000Z
DTSTAMP:20200301T230205Z
UID:6krmac1p64q64b9oc4p3eb9k60p6ab9oc4q30bb4c4r66d1lcosjecb66s@google.com
SEQUENCE:0
CREATED:20191025T221123Z
DESCRIPTION:
LAST-MODIFIED:20191025T221123Z
LOCATION:Portsmouth Dental Care\\, 5228 N Lombard St\\, Portland\\, OR 97203\\\r\n , USA
STATUS:CONFIRMED
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-PT30M
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P1D
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P5D
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTART:20200108T130000Z
DTEND:20200108T153000Z
DTSTAMP:20200301T215713Z
UID:13hu9o9unb1d367aus4c6r0oar@google.com
CREATED:20200301T215614Z
DESCRIPTION:
LAST-MODIFIED:20200301T215625Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Single Wednesdays (diff tzs)
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=America/Los_Angeles:20200107T073000
DTEND;TZID=America/Los_Angeles:20200107T130000
RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20200429T065959Z;BYDAY=TU
DTSTAMP:20200301T215713Z
UID:5psch1be8ro3r3i916snvgitdk@google.com
CREATED:20200301T215520Z
DESCRIPTION:
LAST-MODIFIED:20200301T215520Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Tuesdays
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20200106
DTEND;VALUE=DATE:20200107
RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20200511;BYDAY=MO
DTSTAMP:20200301T215713Z
UID:3jrpqsra7vms1st20g5vnjobue@google.com
CREATED:20200301T215454Z
DESCRIPTION:
LAST-MODIFIED:20200301T215454Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Mondays
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

Interestingly, if I simplify the ics file to 

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:fortesting833@gmail.com
X-WR-TIMEZONE:America/Los_Angeles
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
SUMMARY:Dentist Cleaning
DTSTART:20200417T210000Z
DTEND:20200417T220000Z
DTSTAMP:20200301T230205Z
UID:6krmac1p64q64b9oc4p3eb9k60p6ab9oc4q30bb4c4r66d1lcosjecb66s@google.com
SEQUENCE:0
CREATED:20191025T221123Z
DESCRIPTION:
LAST-MODIFIED:20191025T221123Z
LOCATION:Portsmouth Dental Care\\, 5228 N Lombard St\\, Portland\\, OR 97203\\\r\n , USA
STATUS:CONFIRMED
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-PT30M
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P1D
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P5D
END:VALARM
END:VEVENT
END:VCALENDAR
```
I don't get the exception.

As a further complication, I haven't figured out how to reproduce the original `AttributeError: 'datetime.timezone' object has no attribute 'localize'` error without using my personal gcal's ics file.  I'm going to keep working on seeing if I can reproduce that error.

**Comment by RagingRoosevelt** [comment]
Ok, further development.  

I noticed that the source of the problem was actually originating at [this line](../blob/v0.1.16b0/recurring_ical_events.py#L224) in the `recurring_ical_events` module and was then causing an issue in `dateutil\rrule.py` associated with building the iterator.  I tried upgrading my dateutil package version and **that completely solved the problem**.

So when I was encountering this issue, I was using `python-dateutil==2.6.1`.  After upgrading, I moved to `python-dateutil==2.8.1`.

So I'm not sure what the appropriate corrective action is. Maybe 
* stating `python-dateutil>=2.8.1` in `requirements.txt`?  If we went this route, I'd be happy to try to narrow down which specific version of `dateutil` updated that generator method so that we could be more precise in the `requirements.txt`.
* updating the `RepeatedEvent`'s constructor to fix unruly rules?  I could do some additional exploration to see what's the deal.

Anyhow, here's one of the offending `VEVENT`s:
```
BEGIN:VEVENT
SUMMARY:Dragon Boats
DTSTART;TZID=America/Los_Angeles:20190722T173000
DTEND;TZID=America/Los_Angeles:20190722T183000
DTSTAMP:20200304T085521Z
UID:1jarqa007psjkn0363l86t432q@google.com
SEQUENCE:0
RRULE:FREQ=WEEKLY;UNTIL=20190904;BYDAY=MO,WE;WKST=SU
CREATED:20190722T225925Z
DESCRIPTION:
LAST-MODIFIED:20190801T160613Z
LOCATION:Riverplace Marina\\, 0315 SW Montgomery St\\, Portland\\, OR 97201\\, USA
STATUS:CONFIRMED
TRANSP:OPAQUE
END:VEVENT
```

**Comment by RagingRoosevelt** [comment]
I tracked down the specific change and dateutil version.  In the changelog for 2.7.0, [they stated](https://dateutil.readthedocs.io/en/stable/changelog.html#version-2-7-0): 
> Added support for TZID parameter for DTSTART in rrulestr. Reported and fixed by @ryanpetrello (gh issue #614, gh pr #624)

It looks like they did some bugfixes in [2.7.1](https://dateutil.readthedocs.io/en/stable/changelog.html#version-2-7-1-2018-03-24) because that's the minimum version needed to address this particular `rrule` issue.

If updating the `requirements.txt` is the right path, then I would propose requiring `python-dateutil>=2.7.3` since it addresses some additional `rrule` stuff.  I think an argument could be made for [2.8.0](https://dateutil.readthedocs.io/en/stable/changelog.html#version-2-8-0-2019-02-04) as well, since that update has the most recent changes to `rrule` in dateutil.

**Comment by niccokunzmann** [comment]
Wow, thanks for the work.
Looking at https://pypi.org/project/python-dateutil/#history
I would say it is about 4 tries to find the version which solves this error.

I would go for
> stating python-dateutil>=2.8.1 in requirements.txt
That would solve it for me. Not many people will install older versions and those who do maybe know how to deal with it - I hope.
Since this is an issue of python-dateutil, I do not think, we must test it here.
However, I heard, one should also test one's dependencies. So making it 100% perfect would be adding a test.
With a test, we can narrow errors down in the future.

What do you think?

Maybe, we can also document that certain errors can be removed by updating other packages.

**Comment by RagingRoosevelt** [comment]
Yeah, that seems like a reasonable call.  It looks like dateutil 2.7.0 dropped support for Python 3.2 so that might be an argument against restricting dateutil version in requirements.txt.  I don't think that's too much of a problem, though, and the benefits outweigh the downsides.

**Comment by niccokunzmann** [comment]
@RagingRoosevelt Thanks again for putting in all this work. I created a pull request #33 which closed this issue. You might be interested to check if it really covers the case.
