### ISSUE TITLE
bug: Wont list recurring item

### ISSUE THREAD

**Issue by mrx23dot** [niccokunzmann/python-recurring-ical-events#40]
Wont list recurring item from google calendar for given day:

 s.xhtml
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/London:20180325T100000
DTEND;TZID=Europe/London:20180325T101500
RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=SU
DTSTAMP:20200813T203044Z
UID:48cksquo7kct3npp9jl4j4td1p@google.com
CREATED:20180319T220251Z
DESCRIPTION:
LAST-MODIFIED:20180319T220252Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:test item

**Comment by mrx23dot** [comment]
start_date = (2020, 8, 6)
end_date =   start_date

**Comment by niccokunzmann** [comment]
Hi and thanks for reporting!

`BYDAY=SU` means Sunday. 6th of August 2020 is a Thursday.
Could you tell me more about why this should be listed? Maybe missing parts of the ICS file give a clue.

**Comment by mrx23dot** [comment]
Sorry, my bad I misstyped the date: start_date = (2020, 8, 9)

recurring-ical-events is the only working RRULE capable library, thanks for it!
