### ISSUE TITLE
bug: one day event spans multi day 

### ISSUE THREAD

**Issue by mrx23dot** [niccokunzmann/python-recurring-ical-events#44]
Using: Successfully installed recurring-ical-events-0.1.18b0

I have one full day event in the calendar (made with google calendar):
DTSTART;VALUE=DATE:20200814
DTEND;VALUE=DATE:20200815     -> I guess this is parsed as 8/15/0:00, technically a new day
SUMMARY:test2

When running the attached script the event is reported not only one aug.14 day.
date (2020, 8, 13)
date (2020, 8, 14)
 test2
date (2020, 8, 15)
 test2
date (2020, 8, 16)

Not sure what ical standard says about this, but google is a big player.
[multiday.zip](https://github.com/niccokunzmann/python-recurring-ical-events/files/5099195/multiday.zip)

**Comment by mrx23dot** [comment]
I found the reason:

"For your example, DTSTART=20101220, DTEND=20101221 since the end is **exclusive**."
https://stackoverflow.com/questions/4434766/android-google-calendar-dtstart-dtend/4434927

So subtracting 1sec from DTEND would solve the problem.

**Comment by niccokunzmann** [comment]
Thanks for reporting a solution, too. As I do not have much time at the moment, I would wait for other people to step up. I regard this issue as one of the best to start contributing to this repository.

**Comment by NicoHood** [comment]
I think i found the same issue, reported here:
https://github.com/niccokunzmann/python-recurring-ical-events/issues/60

I dont think that substracting a second is a good idea. We should rather check if it is a `date` object instead of `datetime` and then compare properly.

**Comment by niccokunzmann** [comment]
In #68, the error is reproduced.

**Comment by niccokunzmann** [comment]
This is fixed from version 0.2.2b on.
