### ISSUE TITLE
bug: Recurring multiple day long event reported twice

### ISSUE THREAD

**Issue by NicoHood** [niccokunzmann/python-recurring-ical-events#60]
Hey there.
I created an all day event, starting monday, 7 days long that repeats every week. For the first week it works fine, for the 2nd week it is reported twice. I guess that happens, because the sunday is reported a monday 00:00. I guess that is a common ical feature for all day events? So the end date is considered as start, even though it should be counted as the day before.

Can you follow my thought?

e.g.:
Start: Mon 22.11.2021
End: So 28.11.2021

ical data:
Start: 2021-11-22
End: 2021-11-29 -> This is counted for next week, even though it should only be counted as end.

**Comment by NicoHood** [comment]
Here is a workaround for those that are coming from google:

```py
# Get start and end date of week:
# Requires python 3.8: https://docs.python.org/3/library/datetime.html#datetime.date.fromisocalendar
start = date.fromisocalendar(year, week, 1)
end = start + timedelta(days=7)

events = recurring_ical_events.of(ical).between(start, end)
for event in events:
    event_end = event['DTEND'].dt
    # Fix bug with not filtered end date:
    # https://github.com/niccokunzmann/python-recurring-ical-events/issues/60
    if type(event_end) is date and event_end <= start:
        print('Excluding', event_end, start)
        continue

   # Here you can process the event data...
```

**Comment by niccokunzmann** [comment]
@NicoHood  Thanks for working on this... As there is a workaround, I would guess, it is quite easy to implement. Would you give it a try?

This way the tests will show if the workaround does not have side effects... ;) Let me know if you have any questions.

**Comment by NicoHood** [comment]
I also thought about this but looking at the code and some open TODOs related to the recurring-id I had no idea what your code is doing. Putting another code on top does not seem like a good idea, so I'd have to fully understand your code, and I currently ain't got time to fix that all. But I'd love to help, if I can do otherwise.

**Comment by niccokunzmann** [comment]
Thanks! Reporting this and being in conversation is a great help. I always want to offer to work on this so that the progress does not depend on me alone.

**Comment by niccokunzmann** [comment]
@NicoHood, please check with the current version. It solves #44.

**Comment by NicoHood** [comment]
Seems to work. Thanks a lot for taking the time!

**Comment by niccokunzmann** [comment]
Thanks for checking and closing!
