### ISSUE TITLE
Dropping Support for Python v 3.5, 3.6, 2.7

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python-recurring-ical-events#64]
According to https://endoflife.date/python, these Python versions are end of life.
I am wondering what should be done to drop the support and invite a discussion about it.

- [ ] How do other modules drop support for older Python versions?

To drop support for Python versions 3.5, 3.6 and 2.7, these edits need to be made:

- [ ] setup.py - Python versions, `__version__`
- [ ] travis.yml - remove Python versions
- [ ] README.rst - deprecate the versions

**Comment by NicoHood** [comment]
Makes sense

**Comment by niccokunzmann** [comment]
Closing it for now. The pull request was merged and all Input given.
