### ISSUE TITLE
Accepted Talk at FOSSASIA 2022

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/python-recurring-ical-events#81]
I am excited to announce that I will talk about python-recurring-ical-events at the FOSSASIA 2022 summit in April. I started to create slides here:
https://niccokunzmann.github.io/ical-talk-fossasia-2022/

If you have ideas about what is really good to add to the talk, please comment :)

**Comment by niccokunzmann** [comment]
The talk got accepted and is scheduled: 
https://eventyay.com/e/6b901f56/session/7507
You can also join the conference if you are interested.

**Comment by niccokunzmann** [comment]
I held the talk today. I will update you once the recording is shared.

**Comment by NicoHood** [comment]
Oh nice! Excited to see it!

**Comment by niccokunzmann** [comment]
Hello again!
The video has been published:
https://youtu.be/8l3opDdg92I?t=10369

I would like to link to it but I am wondering where. My current favor would be to add a link with a youtube image below the Research heading.

**Comment by NicoHood** [comment]
You are coding on a smartphone? Really?

**Comment by niccokunzmann** [comment]
Yes, at the moment.
