### ISSUE TITLE
Start time discussion

### ISSUE THREAD

**Issue by NicoHood** [niccokunzmann/python-recurring-ical-events#92]
Hi,
sorry for opening just another issue, but I want to clarify things and would like to have your expert input. I think the library behaves correct, just want to share my findings and want to check if they match with your thoughts.

I try to find out, if an event should be considered inside the timeframe, that you pass to `between()`, specially the start boundary. Let's see some examples:

```
between(2.1. 00:00, 5.1. 00:00) -> the timeframe, sure no correct python syntax

Start - End
1.1.(00:00) - 2.1(00:00) (all day event, 1 day long) -> Not included
1.1. 00:00 - 2.1 00:00 (normal event, 1 day long) -> Not included

1.1. 00:00 - 2.1 01:00 (normal event, 1 day, 1h long) -> Included
2.1. 00:00 - 2.1 01:00 (normal event, 1h long) -> Included
2.1. 00:00 - 2.1 00:00 (normal event, open end/no duration set) -> Included
```

So the basic rule I found is: **The end date must be larger (NOT equal) the `between()` start date, EXCEPT if it is an open-end event with no duration that start EXACTLY on the start date&time**

Is that by your intention? It makes sense to me, I just want to clarify, because I need to implement that same for my REST API backend project.

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/python-recurring-ical-events/issues/92">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/92/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/python-recurring-ical-events/issues/92/pledge.svg">
</picture>
</a>

**Comment by NicoHood** [comment]
In php (laravel) this would look like this:

```php
// Apply filtering
$events = new Event();
if (array_key_exists('after', $input)) {
    // Only include events that end after the specified date
    // OR start at the specified date.
    // This in fact means, that we do not include events that end JUST
    // at the specified date, EXCEPT when they start JUST at that specified date.
    $events = $events->where(function ($query) {
        $after = new Carbon($input['after']);
        $query->where('end', '>', $after)
              ->orWhere('start', '=', $after);
    });
}
if (array_key_exists('before', $input)) {
    // In this case we do only accept events start started BEFORE
    // the specified date. Events start start AND end at the specified
    // date (aka open-end events) will be excluded.
    $events = $events->where('start', '<', new Carbon($input['before']));
}

return new EventResourceCollection($events->get());
```

**Comment by NicoHood** [comment]
This is basically my php code in python:
```py
return (span_start < event_stop or span_start == event_start) and event_start < span_stop
```

**Comment by niccokunzmann** [comment]
If you have this, a zero size span with zero size event is excluding the event. That is what I see without tests.

**Comment by NicoHood** [comment]
But why would you want to allow zero size timespans?

**Comment by niccokunzmann** [comment]
I am closing this as I think, the question has been answered. If not, feel free to open a new issue or reply and open this one!
