### ISSUE TITLE
Params returning incorrect information

### ISSUE THREAD

**Issue by peetysmith** [niccokunzmann/python-recurring-ical-events#95]
Hi. Think that this is a bug but may be my not following something correctly. I've tried to go through the source code but can't see where this info is stored. 

I've created a calendar and then used the **of** and **between** methods to get a subset of events that fall within the given window. From that list I'm trying to get access to the TZID parameter of the dtstart and dtend objects. It seems that the params for the dtstart item are altered by this library. 

**To Reproduce**
```
    for event in combined_calendar.walk('vevent'):
        print(event['dtstart'].params)

    all_events_in_window = recurring_ical_events.of(combined_calendar, keep_recurrence_attributes=True).between(start_date, end_date)
    
    all_events_in_window.sort(key=lambda x: x["dtstart"].dt, reverse=False)
    
    for event in all_events_in_window:
        print(event['dtstart'].params)
```

**Expected behavior**
I would expect the print of the original calendar (combined_calendar) and the filtered calendar (all_events_in_window) to be the same however they are coming out differently. 

For combined_calendar: Parameters({'TZID': 'Dublin, Edinburgh, Lisbon, London'})
For all_events_in_window: Parameters({'VALUE': 'DATE-TIME'})

Again, I'm not sure if there's another way I should be accessing the TZID parameter or if this is a genuine bug. 

Cheers.
Pete

**Comment by niccokunzmann** [comment]
Hi and thanks, could you add
- the output
- the calendar file
- say which two lines differ in the output but should be equal?

That helps me to understand it better and maybe do it ob my computer.

**Comment by niccokunzmann** [comment]
> Again, I'm not sure if there's another way I should be accessing the TZID parameter or if this is a genuine bug.

I had a look again - The TZid might be [inside the datetime object](https://www.geeksforgeeks.org/python-datetime-tzinfo/)... 

Try this:
```
event["dtstart"].dt.tzinfo()
```

**Comment by peetysmith** [comment]
Thanks for the suggestion... I tried the following
`print(appointment["dtstart"].dt.tzinfo())`
Resulting in `TypeError: 'NoneType' object is not callable`

**Comment by niccokunzmann** [comment]
Hm, I think this is ready to receive attention though tests...

**Comment by niccokunzmann** [comment]
@peetysmith, do you have an ICS file where this occurs?

**Comment by niccokunzmann** [comment]
Hm. So what I can say:

this module corrects the `X-WR-TIMEZONE` property. As such combining calendars might be problematic.

can you check it a calendar uses this attribute?

**Comment by peetysmith** [comment]
Hey – sorry Nicco for delay. Let me try and dig out an example ics and accompanying code.

P

From: Nicco Kunzmann ***@***.***>
Reply to: niccokunzmann/python-recurring-ical-events ***@***.***>
Date: Monday, 17 October 2022 at 22:50
To: niccokunzmann/python-recurring-ical-events ***@***.***>
Cc: Peter Smith ***@***.***>, Mention ***@***.***>
Subject: Re: [niccokunzmann/python-recurring-ical-events] Params returning incorrect information (Issue #95)


Hm. So what I can say:

this module corrects the X-WR-TIMEZONE property. As such combining calendars might be problematic.

can you check it a calendar uses this attribute?

**Comment by niccokunzmann** [comment]
No problem! I have time.

**Comment by niccokunzmann** [comment]
@peetysmith - did you find something we could use?

**Comment by niccokunzmann** [comment]
@peetysmith Thanks for reporting this. If this can not be tested, I would like to close this. Maybe, it is not important any more or you found a solution. Let me know!
